// AUTO-GENERATED by scripts/generate-syntax-colors.mjs — do not edit by hand.

export const lightSyntaxColors = {
  "comment": "#6a737d",
  "keyword": "#d73a49",
  "string": "#032f62",
  "constant": "#005cc5",
  "entity": "#6f42c1",
  "support": "#005cc5",
  "entity.name.tag": "#22863a",
  "variable.other": "#24292e",
  "invalid.illegal": "#b31d28",
  "markup.heading": "#005cc5",
  "markup.bold": "#24292e",
  "markup.italic": "#24292e",
  "string.other.link": "#032f62",
  "markup.inline.raw": "#005cc5",
} as const;

export const darkSyntaxColors = {
  "comment": "#6a737d",
  "keyword": "#f97583",
  "string": "#9ecbff",
  "constant": "#79b8ff",
  "entity": "#b392f0",
  "support": "#79b8ff",
  "entity.name.tag": "#85e89d",
  "variable.other": "#e1e4e8",
  "invalid.illegal": "#fdaeb7",
  "markup.heading": "#79b8ff",
  "markup.bold": "#e1e4e8",
  "markup.italic": "#e1e4e8",
  "string.other.link": "#dbedff",
  "markup.inline.raw": "#79b8ff",
} as const;
